django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from . import views
from .views import HomepageView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls),
	
	# search our auth stuff first, then pass the rest off to the base libs
	path('accounts/', include('allauth.urls')),
	path('accounts/', include('django.contrib.auth.urls')),

	path('profiles/', include('profiles.urls')),
	#path('', HomepageView.as_view(), name='home'),
	path('planetary/', include("planetary.urls")),
	path('stellar/', include("stellar.urls")),
	path('ratings/', include('star_ratings.urls', namespace='ratings')),
	path('emails/', include('emails.urls', namespace='emails')),
	path('', include('apod_app.urls')),

]

# Serve media files in development only
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
	import debug_toolbar
	urlpatterns = [
		path(r'^__debug__/', include(debug_toolbar.urls)),
	] + urlpatterns

emails/urls.py
from django.urls import path

from .views import (
	WelcomeView
)

app_name = 'emails'
urlpatterns = [
	path('welcome/', WelcomeView.as_view())
]

planetary/urls.py
from django.urls import path
from .views import PlanetaryListView, PlanetaryTourView

app_name = 'planetary'
urlpatterns = [
    path('', PlanetaryListView.as_view(), name="list"),
    path('planetary/tours/<int:pk>/', PlanetaryTourView.as_view(), name="tour_detail"),
]

    #path('', views.PlanetaryListView.as_view(), name="planetary_list"),
    #path('tour/<int:pk>/', views.PlanetaryTourView.as_view(), name='planetary_tour'),
    

    # path('mercury/', views.mercury_page, name="mercury_page"),
    # path('mars/', views.mars_page, name="mars_page"),
    # path('neptune/', views.neptune_page, name="neptune_page"),
    # path('pluto/', views.pluto_page, name="pluto_page"),
    # path('kepler/', views.kepler_page, name="kepler_page"),
    # path('sedna/', views.sedna_page, name="sedna_page"),
	# path('tour/<int:pk>/', views.PlanetaryTourView.as_view())
    # path('mercury/', views.mercury_page, name="mercury_page"),
    # path('mars/', views.mars_page, name="mars_page"),
    # path('neptune/', views.neptune_page, name="neptune_page"),
    # path('pluto/', views.pluto_page, name="pluto_page"),
    # path('kepler/', views.kepler_page, name="kepler_page"),
    # path('sedna/', views.sedna_page, name="sedna_page"),


planetary/models.py
from django.db import models

class PlanetaryTour(models.Model):
    location_and_orbit = models.TextField()

    about_planet = models.TextField()

    name = models.CharField(max_length=100) #name of tour
    length = models.PositiveIntegerField() #length in days
    num_people = models.PositiveIntegerField() #num of people who can go

    image = models.ImageField(upload_to='planetary_tours/', blank=True, null=True)  # Add this line to store images
    image2 = models.ImageField(upload_to='planetary_tours/', blank=True, null=True)
    image3 = models.ImageField(upload_to='planetary_tours/', blank=True, null=True)
    image4 = models.ImageField(upload_to='planetary_tours/', blank=True, null=True)
    
    link = models.CharField(max_length=100, default='none') #Link to NASA page

    def __str__(self):
        return self.name
    



planetary/views.py

import markdown2
from .models import PlanetaryTour
from django.views.generic import DetailView, ListView

# def planetary(request):
#     return render(request, 'planetary/planetary.html')

class PlanetaryListView(ListView):
    model = PlanetaryTour
    template_name = "planetary/all.html"
    context_object_name = 'planetary_tours'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     print("Context:", context)  # This should print the context in your terminal
    #     return context

    # def get_queryset(self):
    #     return PlanetaryTour.objects.order_by('pk')
    

# class PlanetaryListView(ListView):
#     model = PlanetaryTour
#     template_name = 'planetary.html'  
#     context_object_name = 'planetary_tours'  

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         print("Context:", context)
#         return context
    
#     def get_queryset(self):
#         queryset = super().get_queryset()
#         print(queryset)
#         return queryset


class PlanetaryTourView(DetailView):
    template_name = 'planetary/tour.html'
    model = PlanetaryTour

    def get_object(self, queryset=None):
        # Get the PlanetaryTour object
        planetary_tour = super().get_object(queryset)

        # Convert the Markdown fields to HTML using markdown2
        planetary_tour.location_and_orbit_html = markdown2.markdown(planetary_tour.location_and_orbit)
        planetary_tour.about_planet_html = markdown2.markdown(planetary_tour.about_planet)

        return planetary_tour


# def mercury_page(request):
#     mercury_tour = get_object_or_404(PlanetaryTour, name="Mercury Tour")

#     return render(request, 'planetary/mercury_page.html', {'tour': mercury_tour, })

# def mars_page(request):
#     mars_tour = get_object_or_404(PlanetaryTour, name="Mars Tour")

#     return render(request, 'planetary/mars_page.html', {'tour': mars_tour})

# def neptune_page(request):
#     neptune_tour = get_object_or_404(PlanetaryTour, name="Neptune Tour")

#     return render(request, 'planetary/neptune_page.html', {'tour': neptune_tour})

# def pluto_page(request):
#     pluto_tour = get_object_or_404(PlanetaryTour, name="Pluto Tour")

#     return render(request, 'planetary/pluto_page.html', {'tour': pluto_tour})

# def kepler_page(request):
#     kepler_tour = get_object_or_404(PlanetaryTour, name="Kepler Tour")

#     return render(request, 'planetary/kepler_page.html', {'tour': kepler_tour})

# def sedna_page(request):
#     sedna_tour = get_object_or_404(PlanetaryTour, name="Sedna Tour")

#     return render(request, 'planetary/sedna_page.html', {'tour': sedna_tour})



templates/planetary/all.html

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<h1>Planetary Tours</h1>

<p class="intro-planetary">Welcome to the planetary and exo-planetary tours we offer. Whether you want so stay close to home and 
    explore our solar system or you have a taste for adventure and want to go beyond the reaches of our
    Sun we have just the destination for you. With a variety of planets, dwarf planets, and exoplanets
    you will be sure to find a place that draws you in. </p>
<p class="intro-planetary">From gaseous giants of swirling gases, to terrestrial and rocky planets littered with craters, each body 
    provides its own unique features. Explore worlds unlike no other! </p>

<div class="tour-grid">
    {% for tour in planetary_tours %}
        <div class="tour-item">
            <a href="{% url 'planetary:tour_detail' pk=tour.pk %}">
                <img class="tour-image" src="{{ tour.image.url }}" alt="{{ tour.name }} Image">
            </a>
            <h3>{{ tour.name }}</h3>
        </div>
    {% empty %}
        <li>No planetary tours found</li>
    {% endfor %}
</div>

{% endblock %}



templates/planetary/planetary.html
<!-- templates/planetary.html -->

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<h1>Planetary Tours</h1>

<p class="intro-planetary">Welcome to the planetary and exo-planetary tours we offer. Whether you want so stay close to home and 
    explore our solar system or you have a taste for adventure and want to go beyond the reaches of our
    Sun we have just the destination for you. With a variety of planets, dwarf planets, and exoplanets
    you will be sure to find a place that draws you in. </p>
<p class="intro-planetary">From gaseous giants of swirling gases, to terrestrial and rocky planets littered with craters, each body 
    provides its own unique features. Explore worlds unlike no other! </p>

<div class="col-img">
    <div class="column">
        <a href="{% url 'mercury_page' %}">
            <img src="{% static 'images/mercury.jpg' %}">
        </a>
        <h3>Mercury</h3>

        <p>Largest temperature fluctuations in the solary system</p>
        <p>Covered in craters and ridges</p>
    </div>
    <div class="column">
        <a href="{% url 'mars_page' %}">
            <img src="{% static 'images/mars.png' %}">
        </a>
        <h3>Mars</h3>

        <p>Red dust coating the surface </p>
        <p>Mar's gravity is about 62% that on Earth</p>
    </div>
    <div class="column">
        <a href="{% url 'neptune_page' %}">
            <img src="{% static 'images/neptune.jpg' %}">
        </a>
        <h3>Neptune</h3>

        <p>Highest winds of all the planets</p>
        <p>Beautiful blue atmosphere from the methane gas</p>
    </div>
</div>
<div class="col-img">
    <div class="column">
        <a href="{% url 'pluto_page' %}">
            <img src="{% static 'images/pluto.jpg' %}">
        </a>
        <h3>Pluto</h3>
        
        <p>Located in the Kuiper Belt</p>
        <p>Has five known moons</p>
    </div>
    <div class="column">
        <a href="{% url 'kepler_page' %}">
            <img src="{% static 'images/kepler186f.jpg' %}">
        </a>
        <h3>Kepler 186f</h3>
        
        <p>Found in the constellation Cygnus</p>
        <p>Has an orbital period of 130 Earth days</p>
    </div>
    <div class="column">
        <a href="{% url 'sedna_page' %}">
            <img src="{% static 'images/sedna.jpg' %}">
        </a>
        <h3>Sedna</h3>

        <p>Most distant object in our solar system</p>
        <p>It has a highly elliptical orbit</p>
    </div>
</div>

{% endblock %}

templates/planetary/tour.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load ratings %}
{% load static %}

{% block content %}

<h1>{{ object.name }}</h1>

<div class="center">
    <h3 class="box-title">Location and Orbit</h3>
    <div class="info-item">
        <img class="tour-image" src="{{ object.image2.url }}" alt="{{ object.name }} Image1">
        <div class="info-text">
            <div>{{ object.location_and_orbit_html|safe }}</div>
        </div>
    </div>
    <h3 class="box-title">About</h3>
    <div class="info-item">
        <img class="tour-image" src="{{ object.image3.url }}" alt="{{ object.name }} Image2">
        <div class="info-text">
            <div>{{ object.about_planet_html|safe }}</div>
        </div>
    </div>
    <h3 class="box-title">Tour Info</h3>
    <div class="info-item">
        <img class="tour-image" src="{{ object.image4.url }}" alt="{{ object.name }} Image3">
        <div class="info-text">
            <ul>
                <li>The length of the {{ object.name }} is: {{ object.length }} months</li>
                <li>The total number of people that can register for this tour is: {{object.num_people }}</li>
                <li>For any questions about this tour or any others we offer please reach out. We are hapy to
                    make any needed accomodations or answer any questions relevant to the services we offer.
                </li>
            </ul>
        </div>
    </div>

     <h3 class="box-title">Tour Rating</h3>
    <div class="rating">
        {% ratings object %}
    </div> 

    <div class="button-inline-tour">
        <a class="button-29" href="{{ object.link }}">NASA</a>
    </div>

    <div class="button-inline-tour">
        <a class="button-29" href="{% url 'planetary:list' %}">Back</a>
    </div>
</div>

{% endblock content %}