django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from . import views
from .views import HomepageView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls),
	
	# search our auth stuff first, then pass the rest off to the base libs
	path('accounts/', include('allauth.urls')),
	path('accounts/', include('django.contrib.auth.urls')),

	path('profiles/', include('profiles.urls')),
	#path('', HomepageView.as_view(), name='home'),
	path('planetary/', include("planetary.urls")),
	path('stellar/', include("stellar.urls")),
	path('ratings/', include('star_ratings.urls', namespace='ratings')),
	path('emails/', include('emails.urls', namespace='emails')),
	path('', include('apod_app.urls')),

]

# Serve media files in development only
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
	import debug_toolbar
	urlpatterns = [
		path(r'^__debug__/', include(debug_toolbar.urls)),
	] + urlpatterns

emails/urls.py
from django.urls import path

from .views import (
	WelcomeView
)

app_name = 'emails'
urlpatterns = [
	path('welcome/', WelcomeView.as_view())
]

planetary/urls.py
from django.urls import path
from .views import PlanetaryListView, PlanetaryTourView

app_name = 'planetary'
urlpatterns = [
    path('', PlanetaryListView.as_view(), name="list"),
    path('planetary/tours/<int:pk>/', PlanetaryTourView.as_view(), name="tour_detail"),
]

    #path('', views.PlanetaryListView.as_view(), name="planetary_list"),
    #path('tour/<int:pk>/', views.PlanetaryTourView.as_view(), name='planetary_tour'),
    

    # path('mercury/', views.mercury_page, name="mercury_page"),
    # path('mars/', views.mars_page, name="mars_page"),
    # path('neptune/', views.neptune_page, name="neptune_page"),
    # path('pluto/', views.pluto_page, name="pluto_page"),
    # path('kepler/', views.kepler_page, name="kepler_page"),
    # path('sedna/', views.sedna_page, name="sedna_page"),
	# path('tour/<int:pk>/', views.PlanetaryTourView.as_view())
    # path('mercury/', views.mercury_page, name="mercury_page"),
    # path('mars/', views.mars_page, name="mars_page"),
    # path('neptune/', views.neptune_page, name="neptune_page"),
    # path('pluto/', views.pluto_page, name="pluto_page"),
    # path('kepler/', views.kepler_page, name="kepler_page"),
    # path('sedna/', views.sedna_page, name="sedna_page"),


profiles/urls.py
from django.urls import path

from .views import (
	SpaceTravelerProfileCreateView,
	SpaceTravelerProfileUpdateView,
	SpaceTravelerProfileViewView,
	SpaceTravelerProfilesListView
)

app_name = 'profiles'
urlpatterns = [
	path('', SpaceTravelerProfilesListView.as_view(), name='all'),
	path('create/', SpaceTravelerProfileCreateView.as_view(), name='create'),
	path('<int:pk>/', SpaceTravelerProfileViewView.as_view(), name='view'),
	path('<int:pk>/update/', SpaceTravelerProfileUpdateView.as_view(), name='update'),
]

stellar/urls.py
from django.urls import path, include
from .views import StellarHomeView, StarTourView, ConstellationTourView

urlpatterns = [
    path('stars/<int:pk>/', StarTourView.as_view(), name='star_tour'),
    path('constellations/<int:pk>/', ConstellationTourView.as_view(), name='constellation_tour'),
    path('', StellarHomeView.as_view(), name='stellar_home'),
]

stellar/models.py
from django.db import models
from django.urls import reverse
from star_ratings.models import Rating

class StarTour(models.Model):
    name = models.CharField(max_length=100) #name of Star
    type = models.CharField(max_length=100) #Star Type
    distance = models.CharField(max_length=100) #Distance in light years from Earth
    temp = models.CharField(max_length=100) #Surface Temperature of Star

    home_image = models.ImageField(upload_to='static', default='static/stellar/constellations/BigDipper.jpg')

    image1 = models.ImageField(upload_to='static', default='static/stellar/constellations/BigDipper.jpg')
    image2 = models.ImageField(upload_to='static', default='static/stellar/constellations/BigDipper.jpg')
    image3 = models.ImageField(upload_to='static', default='static/stellar/constellations/BigDipper.jpg')

    about1 = models.CharField(max_length=200) #First  about bullet
    about2 = models.CharField(max_length=200) #Second about bullet
    about3 = models.CharField(max_length=200) #Third  about bullet

    link = models.CharField(max_length=100, default='none') #Link to NASA page

    length = models.PositiveIntegerField() #length in days
    num_people = models.PositiveIntegerField() #num of people who can go

    def __str__(self):
        return self.name

class ConstellationTour(models.Model):
    name = models.CharField(max_length=100) #name of Star
    stars = models.CharField(max_length=100) #Notable stars within constellation

    home_image = models.ImageField(upload_to='static', default='static/stellar/constellations/BigDipper.jpg')

    image1 = models.ImageField(upload_to='static', default='static/stellar/constellations/BigDipper.jpg')
    image2 = models.ImageField(upload_to='static', default='static/stellar/constellations/BigDipper.jpg')
    image3 = models.ImageField(upload_to='static', default='static/stellar/constellations/BigDipper.jpg')

    about1 = models.CharField(max_length=200) #First  about bullet
    about2 = models.CharField(max_length=200) #Second about bullet
    about3 = models.CharField(max_length=200) #Third  about bullet

    link = models.CharField(max_length=100, default='none') #Link to NASA page

    length = models.PositiveIntegerField() #length in days
    num_people = models.PositiveIntegerField() #num of people who can go

    def __str__(self):
        return self.name

stellar/views.py
from django.views.generic import TemplateView, DetailView, ListView
from .models import StarTour, ConstellationTour
from django.views import View
from django.urls import reverse_lazy, reverse

# Create your views here.
class StellarHomeView(ListView):
    template_name = "stellar.html"
    context_object_name = 'startours'
    model = StarTour

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'constellationtours': ConstellationTour.objects.order_by('pk')
        })
        return context

    def get_queryset(self):
        return StarTour.objects.order_by('pk')

class StarTourView(DetailView):
    model = StarTour
    template_name = 'star.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star tours"] = StarTour.objects.all()
        return context
    
class ConstellationTourView(DetailView):
    model = ConstellationTour
    template_name = 'constellation.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["constellation tour"] = ConstellationTour.objects.all()
        return context
    
    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}A Guide To The Galaxy{% endblock title %}</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- for ratings -->
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- for ratings -->
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-custom">
      <div class="container-fluid">
        <a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}">
          <img src="{% static 'images/logo.png' %}" class="logo">
          <p class="navbar-text mb-0">A Guide To The Galaxy</p>
        </a>
        <button class="navbar-toggler" type="button" 
          data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" 
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li><a href="{% url 'planetary:list' %}" class="nav-link px-2 link-light fst-italic" >Planetary</a></li>
            <li><a href="{% url 'stellar_home' %}"class="nav-link px-2 link-light fst-italic">Stellar</a></li>
            <li><a href="{% url 'profiles:all' %}"class="nav-link px-2 link-light fst-italic">Profiles</a></li>
          </ul>
          {% if user.is_authenticated %} 
          <div class="mr-auto">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle link-light" href="#" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  {{ user.username }}
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li><a class="dropdown-item link-dark" href="{% url 'account_change_password' %}">Change password</a></li>
                  <li><hr class="dropdown-divider"></li>
                  
                  {% if profile.pk %}
                    <li><a href="{% url 'profiles:view' pk=profile.pk %}" class="dropdown-item link-dark">Profile</a></li>
                  {% else %}
                    <li><a href="{% url 'profiles:create' %}" class="dropdown-item link-dark fw-bold fst-italic">Create profile!</a></li>
                  {% endif %}
                  <li><hr class="dropdown-divider"></li>
                  
                  {% if user.is_staff %}
                    <li><a href="{% url "admin:index" %}" class="dropdown-item link-dark">Django Admin</a></li>
                    <li><hr class="dropdown-divider"></li>
                  {% endif %}

                  <li><a href="{% url "account_logout" %}" class="dropdown-item link-dark">Logout</a></li>
                </ul>
              </li>
            </ul>
          </div>
          {% else %}
          <ul class="navbar-nav">
            {% comment %} using the bootstrap classes for light links and italics {% endcomment %}
            <li><a href="{% url 'account_login' %}" class="nav-link px-2 link-light fst-italic">Login</a></li>
            <li><a href="{% url 'account_signup' %}" class="nav-link px-2 link-light fst-italic">Sign Up</a></li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>

    <main>
      <div class="container">
          {% block content %}
          <!-- Content from child templates will go here -->
          {% endblock content %}
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <!-- slides on homepage -->
    <script src="{% static "js/slides.js" %}"></script>
</body>
</html>

templates/constellation.html
<!-- templates/planetary/kepler_page.html -->

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load ratings %}
{% load static %}

{% block content %}

<h1>A Guide To {{ object.name }}</h1>

<div class="center">
    <h3 class="box-title">Constellation Details</h3>
    <div class="info-item">
        <img src="{{ object.image1.url }}" class="planet-image">
        <div class="info-text">
            <ul>
                <li style="color:white;">  
                    {{ object.name }}
                </li>
                <li style="color:white;">
                    It is composed of the stars {{ object.stars }}.
                </li>
            </ul>
        </div>
    </div>
    <h3 class="box-title">About</h3>
    <div class="info-item">
        <img src="{{ object.image2.url }}" class="planet-image">
        <div class="info-text">
            <ul>
                <li style="color:white;">
                    {{ object.about1 }} 
                </li>
                <li style="color:white;">
                    {{ object.about2 }} 
                </li>
                <li style="color:white;">
                    {{ object.about3 }} 
                </li>
            </ul>
        </div>
    </div>
    <h3 class="box-title">Tour Info</h3>
    <div class="info-item">
        <img src="{{ object.image3.url }}" class="planet-image">
        <div class="info-text">
            <ul>
                <li style="color:white;">
                    The length of tour to {{ object.name }} is: {{ object.length }} months</li>
                </li>
                <li style="color:white;">
                    The total number of people that can register for this tour is: {{object.num_people }}</li>
                </li>
                <li style="color:white;">
                    For any questions about this tour or any others we offer please reach out. We are hapy to
                    make any needed accomodations or answer any questions relevant to the services we offer.
                </li>
            </ul>
        </div>
    </div>

    <h3 class="box-title">Tour Rating</h3>
    <div class="rating">
        {% ratings object %}
    </div>

    <div class="button-inline-tour">
        <a class="button-29" href="{{ object.link }}">NASA</a>
    </div>
    
    <div class="button-inline-tour">
        <a class="button-29" href="{% url 'stellar_home' %}">Back</a>
    </div>
</div>

{% endblock %}

templates/home.html
<!-- templates/home.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>A Guide To The Galaxy</h1>

<div class="intro"> 
    <p>Whether it's traveling to a far away galaxy or exploring a planet close to home we are here to help. 
        With so many destinations to choose some, each offering their own breath taking features, we are sure there
        will be a destination that speaks to you. Explore the far reaches of our galaxy or take a trip to another. 
        With our comprehensize guide you are sure to get the most out of your trip to a new world!
    </p>
</div>
{% if not user.is_authenticated %}
    <h2>Sign Up and Get Started Today</h2>
    <div class="button-inline">
        <a class="button-29" href="{% url 'account_signup' %}">Sign Up</a>
    </div>
{% elif not profile.pk %}
    <h2>Create your profile</h2>
    <p class="centered pb-0">Welcome, {{ user.username }}! It looks like you haven't made your profile yet. Let's fix that!</p>
    <div class="button-inline mb-4">
        <a href="{% url 'profiles:create' %}" class="button-29">Create Profile</a>
    </div>
{% endif %}

<h2>Explore What Space Has To Offer!</h2>

<div class="border">
    <div class="slideshow-container">
        <div class="slide">
            <img src="{% static 'images/home/mercury.jpg' %}">
        </div>
        <div class="slide">
            <img src="{% static 'images/home/crab.jpg' %}">
        </div>
        <div class="slide">
            <img src="{% static 'images/home/mars.png' %}">
        </div>
        <div class="slide">
            <img src="{% static 'images/home/jupiter.jpg' %}">
        </div>
        <div class="slide">
            <img src="{% static 'images/home/stars.jpg' %}">
        </div>
        <div class="slide">
            <img src="{% static 'images/home/uranus.png' %}">
        </div>
        <div class="slide">
            <img src="{% static 'images/home/vega.jpg' %}">
        </div>

        <a class="prev" onclick="changeSlide(-1)">&#10094;</a>
        <a class="next" onclick="changeSlide(1)">&#10095;</a>
    </div>
</div>

<h2> Astronomy Picture of The Day</h2>
<p class="intro">Enjoy a new image from NASA every day! Ranging from the newest JWST galaxy images to pictures of 
    rare astronomical phenomena each day is something new. 
</p>
<br>
<div>
    <h3 class="apod-title">{{ title }}</h3>
    <p class="apod-date">{{ date }}</p>
    <div class="apod-img"><img src="{{ url }}" alt="{{ title }}"></div>
</div>

<h2>Meet The Developers</h2>
<div class="centered">
    <div class="col">
        <h4 class="person1">Madison D.</h4>
        <p class="about-me">
            I'm studying computer science and astronomy to combine two things I love. In 
            my free time I enjoy playing video games or reading, particularly science fiction. A lover of coding 
            I am constantly exploring what it has to offer. 
        </p>
    </div>
    <div class="col">
        <h4 class="person2">Noah R.</h4>
        <p class="about-me">
            As a giant tech nerd I run my own homelab and am a collector of calculators. Outside of tech
            I enjoy biking and camping and am a proud Eagle Scout. I am also a huge language enthusiast. 
        </p>
    </div>
    <div class="col">
        <h4 class="person3">Soren A.</h4>
        <p class="about-me">
            Hi, my name is Soren. Also a huge tech nerd I am studying computer science and enjoy 
            programming. In my free time I like to develop games. Other than coding I am an avid DnD player. 
        </p>
    </div>
</div>
{% endblock content %}

templates/star.html
<!-- templates/planetary/kepler_page.html -->

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load ratings %}
{% load static %}

{% block content %}

<h1>A Guide To {{ object.name }}</h1>

<div class="center">
    <h3 class="box-title">Star Details</h3>
    <div class="info-item">
        <img src="{{ object.image1.url }}" class="planet-image">
        <div class="info-text">
            <ul>
                <li style="color:white;">  
                    {{ object.name }} is a {{ object.type }} star. 
                </li>
                <li style="color:white;">
                    It is {{ object.distance }} Light-Years away from Earth. 
                </li>
                <li style="color:white;">
                    It has surface temperature of {{ object.temp }} degrees Kelvin. 
                </li>
            </ul>
        </div>
    </div>
    <h3 class="box-title">About</h3>
    <div class="info-item">
        <img src="{{ object.image2.url }}" class="planet-image">
        <div class="info-text">
            <ul>
                <li style="color:white;">
                    {{ object.about1 }} 
                </li>
                <li style="color:white;">
                    {{ object.about2 }} 
                </li>
                <li style="color:white;">
                    {{ object.about3 }} 
                </li>
            </ul>
        </div>
    </div>
    <h3 class="box-title">Tour Info</h3>
    <div class="info-item">
        <img src="{{ object.image3.url }}" class="planet-image">
        <div class="info-text">
            <ul>
                <li style="color:white;">
                    The length of tour to {{ object.name }} is: {{ object.length }} months</li>
                </li>
                <li style="color:white;">
                    The total number of people that can register for this tour is: {{object.num_people }}</li>
                </li>
                <li style="color:white;">
                    For any questions about this tour or any others we offer please reach out. We are hapy to
                    make any needed accomodations or answer any questions relevant to the services we offer.
                </li>
            </ul>
        </div>
    </div>

    <h3 class="box-title">Tour Rating</h3>
    <div class="rating">
        {% ratings object %}
    </div>

    <div class="button-inline-tour">
        <a class="button-29" href="{{ object.link }}">NASA</a>
    </div>
    
    <div class="button-inline-tour">
        <a class="button-29" href="{% url 'stellar_home' %}">Back</a>
    </div>
</div>

{% endblock %}

templates/stellar.html
<!-- templates/stellar.html -->

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<h1>Stellar Tours</h1>

<p class="intro-planetary">Welcome to our Stellar tours where you can learn about our Galaxy's stellar wonders! From constellations 
    to the stars that make them up if you want a guide to the stars you're in the right place! </p>
<p class="intro-planetary">Learn about the Stars of our galaxy and what makes them tick or, whether it be the stars that compose them or the folklore that created them, explore the nature of Earth's constellations! </p>


<div class="tour-grid">
    {% for star in startours %}
        <div class="tour-item">
            <a href="{% url 'star_tour' pk=star.pk %}">
                <img class="tour-image" src="{{ star.home_image.url }}" alt="{{ star.name }} Image">
            </a>
            <h3>{{ star.name }}</h3>
        </div>
    {% endfor %}
</div>

<div class="tour-grid">
    {% for const in constellationtours %}
        <div class="tour-item">
            <a href="{% url 'constellation_tour' pk=const.pk %}">
                <img class="tour-image" src="{{ const.home_image.url }}" alt="{{ const.name }} Image">
            </a>
            <h3>{{ const.name }}</h3>
        </div>
    {% endfor %}
</div>


{% comment %} <div class="col-img">
    <div class="column">
        <a href='stars/1/'><img src="{% static 'images/stars/Betelgeuse.jpg' %}"></a>
        <h3>Betelgeuse</h3>
        <p>A Red Supergiant</p>
        <p>640 Light Years Away!</p>
    </div>
    <div class="column">
        <a href='stars/2/'><img src="{% static 'images/stars/Polaris.jpg' %}"></a>
        <h3>Polaris</h3>
        <p>A Supergiant Cepheid Star</p>
        <p>Also known as "The North Star"</p>
    </div>
    <div class="column">
        <a href='stars/3/'><img src="{% static 'images/stars/Sirius.jpg' %}"></a>
        <h3>Sirius</h3>
        <p>A Main Sequence Star</p>
        <p>The brightest star in the Earth's night sky!</p>
    </div>
</div>
<div class="col-img">
    <div class="column">
        <a href='constellations/1/'><img src="{% static 'images/constellations/BigDipper.jpg' %}"></a>
        <h3>The Big Dipper</h3>
        <p>Part of the larger constellation Ursa Major<p/>
        <p>Known by many names, including "The Plough", "Great Wagon", and "Norther Dipper" to name a few</p>
    </div>
    <div class="column">
        <a href='constellations/2/'><img src="{% static 'images/constellations/Cygnus.jpg' %}"></a>
        <h3>Cygnus</h3>
        <p>Visible from both of Earth's hemispheres!<p/>
        <p>Associated with Greek Mythology.</p>
    </div>
    <div class="column">
        <a href='constellations/3/'><img src="{% static 'images/constellations/Orion.jpg' %}"></a>
        <h3>Orion</h3>
        <p>Takes its name from Greek Mythology<p/>
        <p>Contains two of the brightest stars in Earth's night sky!</p>
    </div>
</div> {% endcomment %}

{% endblock %}