django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from . import views
from .views import HomepageView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls),
	
	# search our auth stuff first, then pass the rest off to the base libs
	path('accounts/', include('allauth.urls')),
	path('accounts/', include('django.contrib.auth.urls')),

	path('profiles/', include('profiles.urls')),
	#path('', HomepageView.as_view(), name='home'),
	path('planetary/', include("planetary.urls")),
	path('stellar/', include("stellar.urls")),
	path('ratings/', include('star_ratings.urls', namespace='ratings')),
	path('emails/', include('emails.urls', namespace='emails')),
	path('', include('apod_app.urls')),

]

# Serve media files in development only
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
	import debug_toolbar
	urlpatterns = [
		path(r'^__debug__/', include(debug_toolbar.urls)),
	] + urlpatterns

emails/urls.py
from django.urls import path

from .views import (
	WelcomeView
)

app_name = 'emails'
urlpatterns = [
	path('welcome/', WelcomeView.as_view())
]

profiles/urls.py
from django.urls import path

from .views import (
	SpaceTravelerProfileCreateView,
	SpaceTravelerProfileUpdateView,
	SpaceTravelerProfileViewView,
	SpaceTravelerProfilesListView
)

app_name = 'profiles'
urlpatterns = [
	path('', SpaceTravelerProfilesListView.as_view(), name='all'),
	path('create/', SpaceTravelerProfileCreateView.as_view(), name='create'),
	path('<int:pk>/', SpaceTravelerProfileViewView.as_view(), name='view'),
	path('<int:pk>/update/', SpaceTravelerProfileUpdateView.as_view(), name='update'),
]

profiles/models.py
from django.conf import settings
from django.conf.global_settings import LANGUAGES
from django.db import models

# Create your models here.


PLANETS = [
    (0, 'Mercury'),
    (1, 'Venus'),
    (2, 'Earth'),
    (3, 'Mars'),
    (4, 'Jupiter'),
    (5, 'Saturn'),
    (6, 'Uranus'),
    (7, 'Neptune'),
    (8, 'Pluto'),
]

SECURITY_QUESTIONS = (
	(0, 'What was the name of your first pet?'),
	(1, 'What street did you grow up on?'),
	(2, "What is your mother's maiden name?"),
	(3, 'Where was your first date?'),
	(4, 'What is the name of your best childhood friend?'),
)


# Create your models here.
class SpaceTravelerProfile(models.Model):
	REQUIRED_FIELDS = [
		'home_planet',
		'language',
		'security_question',
		'security_answer',
	]
	home_planet = models.IntegerField(
		verbose_name='planet', 
		choices=PLANETS, 
		null=True, blank=False
	)
	age = models.PositiveIntegerField(
		null = True,  # allows the database to store this field as null
		blank = True # allows the user to omit this field when registering
	)
	language = models.CharField(
		max_length=10, 
		choices=LANGUAGES, 
		null=True, blank=True
	)
	bio = models.TextField(
		max_length=200, 
		null=True, blank=True
	)
	security_question = models.IntegerField(
		# max_length=2, 
		choices=SECURITY_QUESTIONS, 
		null=True, blank=False
	)
	security_answer = models.CharField(
		max_length=30, 
		null=True, blank=False
	)

	real_account = models.OneToOneField(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		related_name='profile',
		null=True, blank=False,
	)

	# def get_profile_is_user(self):
	# 	return self.pk == self.real_account.pk

	def __str__(self) -> str:
		return f"{self.real_account.username}'s profile" #type:ignore

profiles/forms.py
from django.forms import ModelForm

from .models import SpaceTravelerProfile


class SpaceTravelerProfileForm(ModelForm):
	class Meta:
		model = SpaceTravelerProfile
		fields = [
			'home_planet', 
			'language', 
			'age', 
			'bio', 
			'security_question', 
			'security_answer',
			'real_account',
		]
		exclude = ['real_account']

profiles/views.py
from django.conf import settings
from django.contrib.auth.mixins import (
	AccessMixin, # control what happens if 403
	LoginRequiredMixin, # ensure user is logged in
    UserPassesTestMixin, # extra conditions that, if failed, throw a 403
)
from django.contrib.auth.models import User
from django.db.models.base import Model as Model
from django.core.exceptions import ObjectDoesNotExist
from django.forms import BaseModelForm
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from allauth.socialaccount.models import SocialAccount

from .forms import SpaceTravelerProfileForm
from .models import SpaceTravelerProfile


class SpaceTravelerProfileCreateView(LoginRequiredMixin, UserPassesTestMixin, AccessMixin, CreateView):
	form_class = SpaceTravelerProfileForm
	login_url = settings.LOGIN_URL
	# redirect_field_name = 'index'
	success_url = reverse_lazy('home')
	template_name = 'profiles/create.html'


	def test_func(self, *args, **kwargs) -> bool:
		"""
		Ensure they *don't* already have a profile. If they do, they will be redirected.
		"""
		has_profile = None
		if self.request.user.is_authenticated:
			try:
				SpaceTravelerProfile.objects.get(real_account=self.request.user)
				has_profile = True
			except SpaceTravelerProfile.DoesNotExist:
				has_profile = False
		else:
			has_profile = False

		return not has_profile
		
		
	def handle_no_permission(self):
		"""
		When the currently signed-in user has a profile already, just redirect them to profiles:update instead.
		"""
		return redirect(
			'profiles:update',
			kwargs={
				'pk': SpaceTravelerProfile.objects.get(real_account=self.request.user).pk
			}
		)
		# return redirect('profiles:update', pk=SpaceTravelerProfile.objects.get(real_account=self.request.user).pk)


	# the args here are kinda fucked, but it's worked so far, so it's probably fine
	def get_form(self, form_class: BaseModelForm | None = None) -> BaseModelForm:
		"""
		Set the real_account field (hidden) to link the profile to the actual user account that is currently signed in.
		"""
		form = super().get_form(form_class) #type:ignore
		form.initial['real_account'] = User.objects.get(pk=self.request.user.pk)
		return form


	def form_valid(self, form):
		"""
		Quadruple-check that the real_account field (hidden) is set to the currently signed-in user, then save the form.
		"""
		# get the pending object to be created
		obj: SpaceTravelerProfile = form.save(commit=False)
		# make sure this field is set to the current user
		obj.real_account = User.objects.get(pk=self.request.user.pk)
		# save and commit the object
		obj.save()
		# run the rest of the method from the parent class(es)
		return super().form_valid(form)


class SpaceTravelerProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, AccessMixin, UpdateView):
	model = SpaceTravelerProfile
	form_class = SpaceTravelerProfileForm
	login_url = settings.LOGIN_URL

	# success_url = reverse_lazy('home')
	template_name = 'profiles/update.html'

	permission_denied_message = "You cannot edit other user's profiles."

	# def handle_no_permission(self):
	# 	return redirect('home')

	@property
	def this_object(self) -> SpaceTravelerProfile:
		return super().get_object(self.get_queryset()) #type:ignore

	def test_func(self, *args, **kwargs) -> bool:
		"""Function used by UserPassesTestMixin. Used to verify ownership of the profile to update is of the user."""
		# return super().test_func()
		# thisModel = super().get_object(*args, **kwargs)
		return self.this_object.real_account == self.request.user
	
	def get_success_url(self) -> str:
		return reverse(
			'profiles:view',
			kwargs = { 'pk': self.this_object.pk }
		)


class SpaceTravelerProfileViewView(DetailView):
	model = SpaceTravelerProfile
	template_name = 'profiles/view.html'

	@property
	def this_object(self) -> SpaceTravelerProfile: 
		return super().get_object(self.get_queryset()) #type:ignore

	def get_context_data(self, **kwargs) -> dict:
		context = super().get_context_data(**kwargs)
		# get the user associated with this profile
		user: User = self.this_object.real_account #type:ignore
		context['profile_user'] = user

		# get the social account associated with this profile, if there is one
		try:
			social_account = SocialAccount.objects.get(user=user.pk)
		except ObjectDoesNotExist:
			social_account = None
		finally:
			context['social_account'] = social_account

		return context



class SpaceTravelerProfilesListView(ListView):
	model = SpaceTravelerProfile
	template_name = 'profiles/all.html'

templates/profiles/all.html
{% extends "base.html" %}
{% comment %} {% load static %} {% endcomment %}


{% block title %}Profiles{% endblock title %}

{% block content %}

{% comment %} TODO - make not bad {% endcomment %}


<div class="profiles">
	{% comment %} <ul>
		{% for object in object_list %}
		<li><a href="{% url "profiles:view" pk=object.pk %}">{{ object }}</a></li>
		{% endfor %}
	</ul> {% endcomment %}

	<div class="profiles-grid">
		{% for object in object_list %}
			<div class="card profiles-card" style="width: 18rem;">
				{% comment %} <img class="card-img-top" src="https://placebear.com/g/300/500" alt="Card image cap"> {% endcomment %}
				<div class="card-body profiles-card-body">
					<h5 class="card-title">{{ object.real_account.username }}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{ object.real_account.first_name }} {{ object.real_account.last_name}}</h6>

					<div class="profiles-card-info">
						<p class="card-text"><strong>Home planet:</strong> {{ object.get_home_planet_display }}</p>
						<p class="card-text"><strong>Preferred language:</strong> {{ object.get_language_display }}</p>


						<a href="{% url 'profiles:view' pk=object.pk %}" class="btn btn-primary">View profile</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}

templates/profiles/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% comment %} {% load static %} {% endcomment %}


{% block title %}Create your profile{% endblock title %}

{% block content %}
<h2>Create your profile</h2>

<form action="" method="post">{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-info">Create profile</button>
</form>
{% endblock content %}

templates/profiles/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% comment %} {% load static %} {% endcomment %}


{% block title %}Update your profile{% endblock title %}

{% block content %}
<div class="profiles">
	<h2>Update your profile</h2>
	
	<form action="" method="post">{% csrf_token %}
		<div class="row g-3">
			<!-- Row 1 -->
			<div class="col-md-5">
				{{ form.home_planet|as_crispy_field }}
			</div>
			<div class="col-md-5">
				{{ form.language|as_crispy_field }}
			</div>
			<div class="col-md-2">
				{{ form.age|as_crispy_field }}
			</div>
	
			<!-- Row 2 -->
			<div class="col-12">
				{{ form.bio|as_crispy_field }}
			</div>
	
			<!-- Row 3 -->
			<div class="col-md-6">
				{{ form.security_question|as_crispy_field }}
			</div>
			<div class="col-md-6">
				{{ form.security_answer|as_crispy_field }}
			</div>
	
			<!-- Hidden -->
			<div class="hidden">
				<p>{{ form.real_account }}</p>
			</div>
		</div>
	
		<br />
		<button type="submit" class="btn btn-info">Update profile</button>
	</form>
</div>
{% endblock content %}

templates/profiles/view.html
{% extends "base.html" %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}
{% comment %} {% load static %} {% endcomment %}


{% block title %}Profile{% endblock title %}

{% block content %}

<div class="profiles profiles-detail">
	<h2>{{ profile_user.first_name }} {{ profile_user.last_name }}</h2>
	
	{% if object.real_account == user %}
		<a href="{% url "profiles:update" pk=object.pk %}" class="btn btn-sm btn-primary float-end">Update profile</a>
	{% endif %}
	
	<div class="profiles-part">
		<h3>Bio</h3>
		<p>{{ object.bio }}</p>
	</div>
	
	<div class="profiles-part">
		<h3>Home planet</h3>
		<p>{{ object.get_home_planet_display }}</p>
	</div>
	
	<div class="profiles-part">
		<h3>Preferred Language</h3>
		<p>{{ object.get_language_display }}</p>
	</div>
	
	
	<div class="profiles-part">
		{% if object.real_account == user %}
		<h3>Linked accounts</h3>
		<ul>
			<li>{{ user.username }} - local account</li>
			{% if social_account %}
				<li>{{ user.username }} - {{ social_account.provider|title }}</li>
			{% endif %}
		</ul>
		{% endif %}
	</div>
</div>


{% endblock content %}